VERSION_NUMBER = "1.0.8"

TRPY2PY_MAPPINGS = {
    "dene": "try",
    "olmazsa": "except",
    "en\s+sonda": "finally",
    "döndür": "return",
    "çıkar": "-",
    "topla": "+",
    "konuş": "print",
    "doğru": "True",
    "yanlış": "False",
    "fonksiyon": "def",
    "iken": "while",
    "içe aktar": "import",
    "dan": "from",
    "sınıf": "class",
    "eğer": "if",
    "değilse": "elif",
    "yoksa": "else",
    "için": "for",
    "durdur": "break",
    "devam": "continue",
    "teyit": "assert",
    "fırlat": "raise",
    "ile": "with",
    "olarak": "as",
    "genel": "global",
    "nâyerel": "nonlocal",
    "sil": "del",
    "burdan gönder": "yield from",
    "gönder": "yield",
    "Hiç": "None",
    "kendi": "s elf",
    "aralık": "range",
    "büyük\s+eşit": ">=",
    "küçük/s+eşit": "<=",
    "eşit": "==",
    "büyüktür": ">",
    "küçüktür": "<",
    "içinde": "in",
    "geç": "pass",
    "aç": "open",
    "kapat": "close",
    "ve": "and",
    "ya/s+da": "or"
}
