.TH trpy 1
.SH NAME
py2trpy \- Translate python files to trpy
.SH SYNOPSIS
.B py2trpy
[\fIFLAGS\fR]
.IR scriptfile
.SH DESCRIPTION
.B py2trpy
is a program that translates regular python scripts to trpy
.SH OPTIONS
.TP
.BR \-h ", " \-\-help
Show help message and exit.
.TP
.BR \-v ", " \-\-version
Show version number and exit.
.TP
.BR \-o ", " \-\-output
Specify the name of output file.
.SH SEE ALSO
trpy(1)
.SH AUTHOR
Ali Can Gündüz 2025
.SH LICENSE
This program is licensed under the MIT license. See [1] for details. TL;DR: Do whatever you want as long as you include the original copyright and license notice.
.TP
[1]
https://github.com/al1can/trpy/blob/master/LICENSE



