.TH trpy 1
.SH NAME
by2py \- Translate trpy files to python
.SH SYNOPSIS
.B trpy2py
[\fIFLAGS\fR]
.IR scriptfile
.SH DESCRIPTION
.B trpy2py
is an alias for 'trpy -c'. For more information, look up the manual for trpy(1).
.SH SEE ALSO
trpy(1)
.SH AUTHOR
Ali Can Gündüz 2025
.SH LICENSE
This program is licensed under the MIT license. See [1] for details. TL;DR: Do whatever you want as long as you include the original copyright and license notice.
.TP
[1]
https://github.com/al1can/trpy/blob/master/LICENSE



